runtime: php73
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  
  APP_DEBUG: true
  APP_LOG: errorlog
  APP_KEY: YOUR_APP_KEY
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_CONNECTION: _DB_CONNECTION
  DB_HOST: localhost
  DB_DATABASE: _DB_DATABASE
  DB_USERNAME: _DB_DATABASE
  DB_PASSWORD: _DB_PASSWORD
  DB_SOCKET: /cloudsql/CLOUD_SQL_CONNECTION_NAME

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "CLOUD_SQL_CONNECTION_NAME"