version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    networks:
      - app-network

  #Nginx Service
  webserver:
    build:
      context: .
      dockerfile: Dockernginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    networks:
      - app-network

  #MySQL Service
  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: proyecto
      MYSQL_ROOT_PASSWORD: 1234
      SERVICE_NAME: mysql
    networks:
      - app-network
      
#Docker Networks
networks:
  app-network:
    driver: bridge