apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumen-app
  labels:
    app: lumen-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lumen-app
  template:
    metadata:
      labels:
        app: lumen-app
    spec:
      containers:
      - name: lumen-app
        image: IMAGE
        env:
        - name: DB_HOST
          value: "_DB_HOST"
        - name: DB_CONNECTION
          value: "_DB_CONNECTION"
        - name: DB_PORT
          value: "_DB_PORT"
        - name: DB_DATABASE
          value: "_DB_DATABASE"
        - name: DB_USERNAME
          value: "_DB_USERNAME"
        - name: DB_PASSWORD
          value: "_DB_PASSWORD"
