name: Laravel
on:
  push:
    branches: [ master ]
jobs:
  laravel-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: StephaneBour/actions-php-lint@7.4

  laravel-tests:
    needs: laravel-linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
  
  docker-build-and-push:
    needs: laravel-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      run: |
        docker build . -t us.gcr.io/${{secrets.GKE_PROJECT_ID }}/docker_test:${GITHUB_SHA::8} -t us.gcr.io/${{ secrets.GKE_PROJECT_ID }}/docker_test:latest
        echo ${{secrets.GCP_KEY_FILE}} | base64 -d > account.json
        cat account.json | docker login -u _json_key --password-stdin https://us.gcr.io
        docker push us.gcr.io/${{ secrets.GKE_PROJECT_ID }}/docker_test
        docker logout
  
  k8-deploy:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GKE_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_KEY_FILE }}
          export_default_credentials: true
      - run: |-
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials 'cluster-1' --zone ${{secrets.GKE_ZONE}} --project ${{ secrets.GKE_PROJECT_ID }}
          cat k8s/deployment.yaml
          kubectl set image -f k8s/deployment.yaml lumen-app=us.gcr.io/${{secrets.GKE_PROJECT_ID }}/docker_test:${GITHUB_SHA::8} --local -o yaml > k8s/deployment.yaml
          cat k8s/deployment.yaml
          kubectl set env -f k8s/deployment.yaml lumen-app DB_HOST=${{ secrets.DB_HOST }} --local -o yaml > k8s/deployment.yaml
          kubectl set env -f k8s/deployment.yaml lumen-app DB_CONNECTION=${{ secrets.DB_CONNECTION }} --local -o yaml > k8s/deployment.yaml
          kubectl set env -f k8s/deployment.yaml lumen-app DB_PORT=${{ secrets.DB_PORT }} --local -o yaml > k8s/deployment.yaml
          kubectl set env -f k8s/deployment.yaml lumen-app DB_DATABASE=${{ secrets.DB_DATABASE }} --local -o yaml > k8s/deployment.yaml
          kubectl set env -f k8s/deployment.yaml lumen-app DB_USERNAME=${{ secrets.DB_USERNAME }} --local -o yaml > k8s/deployment.yaml
          kubectl set env -f k8s/deployment.yaml lumen-app DB_PASSWORD=${{ secrets.DB_PASSWORD }} --local -o yaml > k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml