name: Laravel

on:
  push:
    branches: [ master ]
jobs:
  laravel-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: StephaneBour/actions-php-lint@7.4
      
  laravel-tests:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
  
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      run: |
        docker build . -t us.gcr.io/proyecto-prueba-23people/docker_test:${GITHUB_SHA::8} -t us.gcr.io/proyecto-prueba-23people/docker_test:latest
        echo ${{secrets.GCP_KEY_FILE}} | base64 -d > account.json
        cat account.json | docker login -u _json_key --password-stdin https://us.gcr.io
        docker push us.gcr.io/proyecto-prueba-23people/docker_test
        docker logout
  
  k8-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: 'proyecto-prueba-23people'
          service_account_key: ${{ secrets.GCP_KEY_FILE }}
          export_default_credentials: true
      - run: |-
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials 'cluster-1' --zone "us-central1-c" --project 'proyecto-prueba-23people'
          kubectl get pods
